package fr.acinq.hc.app


object HC {
  final val HC_INVOKE_HOSTED_CHANNEL_TAG = 65535
  final val HC_INIT_HOSTED_CHANNEL_TAG = 65533
  final val HC_LAST_CROSS_SIGNED_STATE_TAG = 65531
  final val HC_STATE_UPDATE_TAG = 65529
  final val HC_STATE_OVERRIDE_TAG = 65527
  final val HC_HOSTED_CHANNEL_BRANDING_TAG = 65525
  final val HC_REFUND_PENDING_TAG = 65523
  final val HC_QUERY_PUBLIC_HOSTED_CHANNELS_TAG = 65521
  final val HC_REPLY_PUBLIC_HOSTED_CHANNELS_END_TAG = 65519

  final val PHC_ANNOUNCE_GOSSIP_TAG = 65517
  final val PHC_ANNOUNCE_SYNC_TAG = 65515
  final val PHC_UPDATE_GOSSIP_TAG = 65513
  final val PHC_UPDATE_SYNC_TAG = 65511

  val announceTags: Set[Int] =
    Set(PHC_ANNOUNCE_GOSSIP_TAG, PHC_ANNOUNCE_SYNC_TAG,
      PHC_UPDATE_GOSSIP_TAG, PHC_UPDATE_SYNC_TAG)

  val messageTags: Set[Int] =
    Set(HC_INVOKE_HOSTED_CHANNEL_TAG, HC_INIT_HOSTED_CHANNEL_TAG, HC_LAST_CROSS_SIGNED_STATE_TAG,
      HC_STATE_UPDATE_TAG, HC_STATE_OVERRIDE_TAG, HC_HOSTED_CHANNEL_BRANDING_TAG, HC_REFUND_PENDING_TAG,
      HC_QUERY_PUBLIC_HOSTED_CHANNELS_TAG, HC_REPLY_PUBLIC_HOSTED_CHANNELS_END_TAG)
}
